apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: status-page-ingress
  namespace: caritas
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - status.oriso.site
    secretName: status-oriso-site-tls
  rules:
  - host: status.oriso.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: status-page
            port:
              number: 9200

